config/routes.rb
Rails.application.routes.draw do
  get 'my_badges/index'

  get 'badges/name'
  resources :badges
  resources :my_badges
  resources :users
  resource :sessions
  resources :maps
  resources :sign_out
  resources :pictures do
    resources :comments
  end
  resources :welcome
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
	has_many :pictures 
	has_many :users, through: :pictures
end

app/models/picture.rb
class Picture < ActiveRecord::Base
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	belongs_to :user
	belongs_to :badge
	before_post_process :load_exif

	validates_attachment_presence :image
	validates_attachment_content_type :image, :content_type => ['image/jpeg']
	def b_url(image_size)
		self.image.url(image_size).gsub("//s3.amazonaws.com/", "//s3-us-west-1.amazonaws.com/")
	end
	
	def load_exif

	  exif = EXIFR::JPEG.new(image.queued_for_write[:original].path)
	 
	  # return if exif.nil? or not exif.exif?
	  self.date = exif.date_time.to_date
	  self.latitude = exif.gps.latitude
	  self.longitude = exif.gps.longitude
	  rescue
	    false
	end


end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
	# this will validates email registration
	before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, length: { minimum: 6 }, on: :create
	has_many :pictures
	has_many :badges, through: :pictures
	
	# use for gem bcrypt
	has_secure_password
	
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
respond_to :json, :html
  
  def index
  	@badges = Badge.all
  	@picture = Picture.new
  	respond_with @badges
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def index
		@pictures = Picture.where("badge_id > 0" )

	end
	def show
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	


	
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	respond_to :json, :html
	def index
		@pictures = Picture.paginate(:page => params[:page], :per_page => 12)
		respond_with @pictures
		# @pictures = Picture.latitude
		# @pictures = Picture.longitude
	end

	# def all
	# 	@pictures = Picture.all.reverse.paginate(:page => params [:page], :per_page => 10)
	# end

	def show
		respond_with @pictures
		# @picture = Picture.find(params[:id])
		# @pictures = Picture.all
	end

	def new
		@picture = Picture.new
	end

	def edit

	end

	def create
		@picture = current_user.pictures.new(post_params)
		if @picture.save
			respond_to do |format|
	        format.html { redirect_to users_path }
	        format.json { render json: @picture, status: :created }
		    end
		else
			respond_to do |format|
	        format.html { render 'new' }
	        format.json { render json: @picture.errors, status: :unprocessable_entity }
		    end
		end
	end

	def update

	end

	def destroy

		Picture.find(params[:id]).destroy
		respond_to do |format|
	      format.html { redirect_to users_path }
	      format.json { render json: { head: :ok } }
		end
	end


	private
		
		def post_params
			params.require(:picture).permit(:caption, :image, :badge_id, :name)
		end

		def set_post
			@picture = Picture.find(params[:id])
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user == nil || !@user.authenticate(params[:session][:password])
			flash[:error] = "Invalid email!! Password combination!!"
			render 'new'
		else
			session[:remember_token] = @user.id
			@current_user = @user
			redirect_to users_path
		end
	end

	def destroy
		session.delete(:remember_token)
		redirect_to sign_out_index_path
	end
end

app/controllers/sign_out_controller.rb
class SignOutController < ApplicationController
	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
respond_to :json, :html

	def index
		@pictures = current_user.pictures.paginate(:page => params[:page], :per_page => 8)
		@badges = Badge.all
		respond_with @pictures
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@pictures = @user.pictures.all
		
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Let the Hunt begin!!"
			session[:remember_token] = @user.id.to_s
			redirect_to users_path
		else
			flash[:failure] = "Please enter a real email address and an 8 digit password"
			render :new
		end
	end

	
	protected

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		if session[:remember_token]
			@current_user ||= session[:remember_token]&& User.find(session[:remember_token])
		else
			@current_user = nil
		end
	end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/my_badges_helper.rb
module MyBadgesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user
		if session[:remember_token]
			@current_user ||= session[:remember_token]&& User.find(session[:remember_token])
		else
			@current_user = nil
		end
	end

end

app/helpers/sign_out_helper.rb
module SignOutHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
index.html.erb

app/views/comments/new.html.erb
new.html.erb

app/views/comments/show.html.erb
show.html.erb

app/views/maps/index.html.erb
 
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<body id="mapindex">
 <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>   
 
<div class="row" >
    <div class="large-12 columns" >
      <h5>Badges can be earned through these spots</h5>
        <div id="map-canvas"></div>
    </div>
</div>
 
   
   
 
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Rocky Thach Zeke</p>
        </div>
      </div>
    </div>
  </footer>
</body>

<script type="text/javascript">

    handler = Gmaps.build('Google');

    handler.buildMap ({ provider: {zoom: 16, provider_key: "AIzaSyDJJPOQH24cT6ETa9IZacS7NENpUt2MKzA"}, internal: {id: 'map-canvas'}}, function(){
    <% @pictures.each do |p|%>
    markers = handler.addMarkers([
    {lat: <%=p.latitude%>,
    lng: <%=p.longitude%>
	}
    
  ]);
    <%end%>
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();



});

</script>

app/views/maps/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
 <body>
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Tresure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>
<h1>Badges can be earn through these spots</h1>

<div id="map-canvas"></div>

</body>

app/views/sign_out/index.html.erb
 <body id="signout">
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>
<p>Hope to see you again soon</p>

</body>

app/views/welcome/index.html.erb
<body id ="welcome">
 <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>

  <div class="row" style ="margin-top: 50px">
  	<aside class="large-3 columns" class ="text-center">
      <ul data-orbit data-options="animation:fade; navigation_arrows:false; bullets:false;slide_number: false; animation:'fade';timer_speed: 900" class ="text-center">
        <li>
         <%= image_tag "badges/cinderella.png"%>
        </li>
        <li>
         <%= image_tag "badges/belle.png"%>
        </li>
        <li>
         <%= image_tag "badges/ariel.png"%>
        </li>
        <li>
         <%= image_tag "badges/aurora.png"%>
        </li>
        <li>
         <%= image_tag "badges/snowwhite.png"%>
        </li>
        <li>
         <%= image_tag "badges/anna.png"%>
        </li>
        <li>
         <%= image_tag "badges/elsa.png"%>
        </li>
        <li>
         <%= image_tag "badges/merida.png"%>
        </li>
        <li>
         <%= image_tag "badges/rapunzel.png"%>
        </li>
        <li>
         <%= image_tag "badges/alice.png"%>
        </li>
        <li>
         <%= image_tag "badges/attaant.png"%>
        </li>
        <li>
         <%= image_tag "badges/baloo.png"%>
        </li>
        <li>
         <%= image_tag "badges/beast.png"%>
        </li>
        <li>
         <%= image_tag "badges/bobafett.png"%>
        </li>
        <li>
         <%= image_tag "badges/bolt.png"%>
        </li>
        <li>
         <%= image_tag "badges/boo.png"%>
        </li>
        <li>
         <%= image_tag "badges/brerfox.png"%>
        </li>
        <li>
         <%= image_tag "badges/brerrabbit.png"%>
        </li>
        <li>
         <%= image_tag "badges/buzz.png"%>
        </li>
        <li>
         <%= image_tag "badges/captainhook.png"%>
        </li>
        <li>
         <%= image_tag "badges/chewy.png"%>
        </li>
        <li>
         <%= image_tag "badges/chipndale.png"%>
        </li>
        <li>
            <%= image_tag "badges/aladdin.png"%>
          </li>
        <li>
         <%= image_tag "badges/cruella.png"%>
        </li>
        <li>
         <%= image_tag "badges/daisy.png"%>
        </li>
        <li>
         <%= image_tag "badges/darthvader.png"%>
        </li>
        <li>
         <%= image_tag "badges/donald.png"%>
        </li>
        <li>
         <%= image_tag "badges/eeyore.png"%>
        </li>
        <li>
         <%= image_tag "badges/elastigirl.png"%>
        </li>
        <li>
         <%= image_tag "badges/fairygodmother.png"%>
        </li>
        <li>
         <%= image_tag "badges/fawn.png"%>
        </li>
        <li>
         <%= image_tag "badges/flick.png"%>
        </li>
        <li>
         <%= image_tag "badges/frozone.png"%>
        </li>
        <li>
         <%= image_tag "badges/gaston.png"%>
        </li>
        <li>
         <%= image_tag "badges/genie.png"%>
        </li>
        <li>
         <%= image_tag "badges/gepetto.png"%>
        </li>
        <li>
         <%= image_tag "badges/goofy.png"%>
        </li>
        <li>
         <%= image_tag "badges/greenarmymen.png"%>
        </li>
        <li>
         <%= image_tag "badges/handyman.png"%>
        </li>
        <li>
         <%= image_tag "badges/iridessa.png"%>
        </li>
        <li>
         <%= image_tag "badges/jafar.png"%>
        </li>
        <li>
         <%= image_tag "badges/jesse.png"%>
        </li>
        <li>
         <%= image_tag "badges/jiminy.png"%>
        </li>
        <li>
         <%= image_tag "badges/launchpad.png"%>
        </li>
        <li>
         <%= image_tag "badges/madhatter.png"%>
        </li>
        <li>
         <%= image_tag "badges/maleficent.png"%>
        </li>
        <li>
         <%= image_tag "badges/marypoppins.png"%>
        </li>
        <li>
         <%= image_tag "badges/max.png"%>
        </li>
        <li>
         <%= image_tag "badges/meg.png"%>
        </li>
        <li>
         <%= image_tag "badges/mickey.png"%>
        </li>
        <li>
         <%= image_tag "badges/minnie.png"%>
        </li>
        <li>
         <%= image_tag "badges/mrincredible.png"%>
        </li>
        <li>
         <%= image_tag "badges/mrsmee.png"%>
        </li>
        <li>
         <%= image_tag "badges/mulan.png"%>
        </li>
        <li>
         <%= image_tag "badges/peterpan.png"%>
        </li>
        <li>
         <%= image_tag "badges/piglet.png"%>
        </li>
        <li>
         <%= image_tag "badges/pinocchio.png"%>
        </li>
        <li>
         <%= image_tag "badges/pluto.png"%>
        </li>
        <li>
         <%= image_tag "badges/pooh.png"%>
        </li>
        <li>
         <%= image_tag "badges/princeeric.png"%>
        </li>
        <li>
         <%= image_tag "badges/queenofhearts.png"%>
        </li>
        <li>
         <%= image_tag "badges/r2d2.png"%>
        </li>
        <li>
         <%= image_tag "badges/rabbit.png"%>
        </li>
        <li>
         <%= image_tag "badges/rafiki.png"%>
        </li>
        <li>
         <%= image_tag "badges/rosetta.png"%>
        </li>
        <li>
         <%= image_tag "badges/santa.png"%>
        </li>
        <li>
         <%= image_tag "badges/scrooge.png"%>
        </li>
        <li>
         <%= image_tag "badges/sevendwarfs.png"%>
        </li>
        <li>
         <%= image_tag "badges/silvermist.png"%>
        </li>
        <li>
         <%= image_tag "badges/snowwhitequeen.png"%>
        </li>
        <li>
         <%= image_tag "badges/stormtrooper.png"%>
        </li>
        <li>
         <%= image_tag "badges/sully.png"%>
        </li>
        <li>
         <%= image_tag "badges/tigger.png"%>
        </li>
        <li>
         <%= image_tag "badges/timon.png"%>
        </li>
        <li>
         <%= image_tag "badges/tink.png"%>
        </li>
        <li>
         <%= image_tag "badges/whiterabbit.png"%>
        </li>
        <li>
         <%= image_tag "badges/woody.png"%>
        </li>
		</ul>
 
      <!-- <div class="panel">
        <h5>Featured</h5>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
        <a href="#">Read More →</a>
      </div> -->
    </aside>
    <div class="large-9 columns" role="content">
 
      <article>
 
        <h2>Disney Treasure Hunt<% if !current_user%>
          	<%= link_to "Sign Up", new_user_path, class: "button tiny radius"%> 
          	<%else%>
          	<%end%>
        </h2>
            <div class="panel radius", style = "opacity:0.7">
			  <h4>Explore the hidden treasures of Disney Land</h4>
				<p>Receive rewards for taking pictures with Disney Characters while making a digital scrapbook of fun memories at Disneyland!</p>

				<p>Disney Picture Collector is a fast, beautiful and fun way to go on a Disney Character Treasure hunt at Disneyland/ Disneyland California Adventure Park.</p>  

				<p>Take a picture of yourself with a Disney character and post the picture to Disney Picture Collector. Once the picture is posted, you will receive a reward of a digital badge of the character you took the picture with that you can share with friends and family.</p>

				<p>It’s a new and exciting way to experience Disneyland!</p>

				<p>There are 77 digital badges… can you collect them all?</p>
			</div>
 
      </article>
 
    </div>
  </div>
   <br>
   <br>
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Rocky Thach and Zeke.</p>
        </div>
      </div>
    </div>
  </footer>
</body>
<!-- <div class="row">
  <div class="large-4 columns" id ="badges">
	  	<ul data-orbit data-options="animation:fade; navigation_arrows:false; bullets:false;slide_number: false; animation:'fade';timer_speed: 900">
		  <li>
		    <%= image_tag "Cinderella.png"%>
		  </li>
		  <li>
		    <%= image_tag "elsa.png"%>
		  </li>
		  <li>
		    <%= image_tag "meg.png"%>
		  </li>
		  <li>
		    <%= image_tag "whiterabbit.png"%>
		  </li>
		  <li>
		    <%= image_tag "woody.png"%>
		  </li>
		</ul>
  </div>

  <div class="large-8 columns" id ="hunt">
  	<h2 class="text-left">The hunt</h2>
  	<% if !current_user%>
  	<%= link_to "Sign Up", new_user_path, class: "button tiny radius"%> 
  	<%else%>
  	<%end%>
	  	<div class="panel radius", style = "opacity:0.7">
		  <h4>Explore the hidden treasure of Disney Land</h4>
			<p>Receive rewards for taking pictures with Disney Characters while making a digital scrapbook of fun memories at Disneyland!</p>

			<p>Disney Picture Collector is a fast, beautiful and fun way to go on a Disney Character Treasure hunt at Disneyland/ Disneyland California Adventure Park.</p>  

			<p>Take a picture of yourself with a Disney character and post the picture to Disney Picture Collector. Once the picture is posted, you will receive a reward of a digital badge of the character you took the picture with that you can share with friends and family.</p>

			<p>It’s a new and exciting way to experience Disneyland!</p>

			<p>There are 77 digital badges… can you collect them all?</p>
		</div>
  </div>
</div> -->