config/routes.rb
Rails.application.routes.draw do
  get 'my_badges/index'

  get 'badges/name'
  resources :badges
  resources :my_badges
  resources :users
  resource :sessions
  resources :maps
  resources :sign_out
  resources :pictures do
    resources :comments
  end
  resources :welcome
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
	has_many :pictures 
	has_many :users, through: :pictures
end

app/models/picture.rb
class Picture < ActiveRecord::Base
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	belongs_to :user
	belongs_to :badge
	before_post_process :load_exif

	validates_attachment_presence :image
	validates_attachment_content_type :image, :content_type => ['image/jpeg']
	def b_url(image_size)
		self.image.url(image_size).gsub("//s3.amazonaws.com/", "//s3-us-west-1.amazonaws.com/")
	end
	
	def load_exif

	  exif = EXIFR::JPEG.new(image.queued_for_write[:original].path)
	 
	  # return if exif.nil? or not exif.exif?
	  self.date = exif.date_time.to_date
	  self.latitude = exif.gps.latitude
	  self.longitude = exif.gps.longitude
	  rescue
	    false
	end


end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
	# this will validates email registration
	before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, length: { minimum: 6 }, on: :create
	has_many :pictures
	has_many :badges, through: :pictures
	
	# use for gem bcrypt
	has_secure_password
	
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
respond_to :json, :html
  
  def index
  	@badges = Badge.all
  	@picture = Picture.new
  	respond_with @badges
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def index
		@pictures = Picture.where("badge_id > 0" )

	end
	def show
	end
end

app/controllers/my_badges_controller.rb
class MyBadgesController < ApplicationController
	
  def index
  	@badges = current_user.badges
  	
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	


	
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	respond_to :json, :html
	def index
		@pictures = Picture.paginate(:page => params[:page], :per_page => 12)
		respond_with @pictures
		# @pictures = Picture.latitude
		# @pictures = Picture.longitude
	end

	# def all
	# 	@pictures = Picture.all.reverse.paginate(:page => params [:page], :per_page => 10)
	# end

	def show
		respond_with @pictures
		# @picture = Picture.find(params[:id])
		# @pictures = Picture.all
	end

	def new
		@picture = Picture.new
	end

	def edit

	end

	def create
		@picture = current_user.pictures.new(post_params)
		if @picture.save
			respond_to do |format|
	        format.html { redirect_to users_path }
	        format.json { render json: @picture, status: :created }
		    end
		else
			respond_to do |format|
	        format.html { render 'new' }
	        format.json { render json: @picture.errors, status: :unprocessable_entity }
		    end
		end
	end

	def update

	end

	def destroy

		Picture.find(params[:id]).destroy
		respond_to do |format|
	      format.html { redirect_to users_path }
	      format.json { render json: { head: :ok } }
		end
	end


	private
		
		def post_params
			params.require(:picture).permit(:caption, :image, :badge_id, :name)
		end

		def set_post
			@picture = Picture.find(params[:id])
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user == nil || !@user.authenticate(params[:session][:password])
			flash[:error] = "Invalid email!! Password combination!!"
			render 'new'
		else
			session[:remember_token] = @user.id
			@current_user = @user
			redirect_to users_path
		end
	end

	def destroy
		session.delete(:remember_token)
		redirect_to sign_out_index_path
	end
end

app/controllers/sign_out_controller.rb
class SignOutController < ApplicationController
	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
respond_to :json, :html

	def index
		@pictures = current_user.pictures.paginate(:page => params[:page], :per_page => 8)
		@badges = Badge.all
		respond_with @pictures
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@pictures = @user.pictures.all
		
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Let the Hunt begin!!"
			session[:remember_token] = @user.id.to_s
			redirect_to users_path
		else
			flash[:failure] = "Please enter a real email address and an 8 digit password"
			render :new
		end
	end

	
	protected

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		if session[:remember_token]
			@current_user ||= session[:remember_token]&& User.find(session[:remember_token])
		else
			@current_user = nil
		end
	end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/my_badges_helper.rb
module MyBadgesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def current_user
		if session[:remember_token]
			@current_user ||= session[:remember_token]&& User.find(session[:remember_token])
		else
			@current_user = nil
		end
	end

end

app/helpers/sign_out_helper.rb
module SignOutHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges/index.html.erb
 <body id="collection">
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>
<h1 style="text-align:center">Badge Gallery</h1>
<div x-ng-app="">
  <div x-ng-init="badges=<%=Badge.all.to_json%>" class="row">
    <%if !current_user%>
        <div x-ng-repeat="b in badges" class="large-3 columns small-6 columns">
          <div class="panel">
              <img ng-src="/assets/badges/{{b.url}}"%>
              {{b.name}}
          </div>
        </div>
      <%else%>
        <% @badges.each do |b|%>
          <div class="large-3 columns small-6 columns">
              <div class="panel">
                  <%= image_tag "badges/" + b.url%>
                  <%= b.name%>
                  <%= form_for @picture do |f| %>
                    <%= f.hidden_field :badge_id ,value: b.id.to_s %>
                    <%= f.file_field :image %>
                    <%= f.submit%>
                  <% end %> 
              </div>
          </div>
        <%end%>
    <%end%>    
  </div>
</div><!--close the ng-app -->


  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Rocky Thach and Zeke.</p>
        </div>
        
      </div>
    </div>
  </footer>
</body>

app/views/pictures/edit.html.erb
edit.html.erb

app/views/pictures/index.html.erb
<body id="pictureindex">
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav> 
<!-- end of nav bar -->
<!-- begin the display -->
   <div class="row" style="margin-top:30px">
    <div class ="panel callout radius">
    <div class="large-12 columns" >
        <%= image_tag "gallery.jpg" %>
  </div>
      
    <div class="large-12 columns" style="margin-top:20px">
   
            <div class="hide-for-small panel">
              <h3 style="text-align:center">Memories</h3>
              <h5 class="subheader" style="text-align:center">Photos of our Disney guests creating memories and earning badges
              </h5>
            </div>
          </div>

    <div class="large-12 columns">
            <div class="row">
              <div class="large-12 columns">
                <div class="row">
                  <ul class="clearing-thumbs" data-clearing>
                  <% @pictures.each do |p| %>
                  <li class="large-3 medium-4 small-6 columns" style="margin-right:0px">
                      <a href=<%=p.b_url(:original)%>><%= image_tag p.b_url(:medium) %></a>
                        <p style="margin-bottom:0px">Taken on: <%= p.date%></p>
                            <%if p.badge%>
                         <td>Badge: <a href="#" data-reveal-id="myModal"><%=p.badge.name%></a>
                          <div id="myModal" class="reveal-modal" data-reveal>
                          <div id="badge_earned"></div>
                          <a class="close-reveal-modal">&#215;</a>
                        </div>
                         </td>
                         <%else%>
                         <td>Badge: n/a</td>
                        <%end%>
                  <% end %>
                </div>
             <!--  <div class="row"> -->  
              <div class="digg_pagination">
                  <div class="page_info" >
                    <%= page_entries_info @pictures %>
                  </div>
                  <%= will_paginate @pictures, :container => false %>
                </div>
             <!--  </div> -->
         
        <div class="row" style ="margin-top:15px">
          <div class="large-12 columns">
            <div class="panel">
              <div class="row">

                <div class="large-2 small-6 columns">
                  <%=image_tag "mickey.png" %>
                </div>

                <div class="large-10 small-6 columns">
                  <strong>This Site Is Managed By<hr/></strong>
                  <p>Rocky Thach and Zeke</p>
                </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
       </div>
  </div>

          <footer class="row">
            <div class="large-12 columns"><hr/>
              <div class="row">
                <div class="large-6 columns">
                  <p>© Copyright no one at all. Go to town.</p>
                </div>
              </div>
            </div>
          </footer>
    </div>
  </div>
</body>

<!-- <h1>How did they earn the badges???</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Caption</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |p| %>
      <tr>
        <td><%= image_tag p.image(:medium) %></td>
        <td><%= p.caption %></td>
        <td><%= p.date%></td>
        <td><label>Lat:</label><%= p.latitude%></td>
        <td><label>Long:</label><%= p.longitude%></td>
        <td><%= link_to 'Delete',p, method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

app/views/pictures/new.html.erb
 <body>
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>
<!-- end of nav bar -->
<!-- begin the display -->
<fieldset>
<legend>Add a picture</legend>
<%= form_for @picture, :html => { :multipart => true } do |f| %>

  <%= f.file_field :image, class: 'form-control' %>
  <%= f.submit "Add happiness", class: 'button radius'%>
<% end %> 
</fieldset>
</body>

app/views/pictures/show.html.erb
<p>This will display the list of all the pictures taken by every users</p>

app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<body id="userpictures">
  <nav class="top-bar" data-topbar >
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <%if !current_user%>
        <li ><%= link_to 'Badge Gallery', badges_path%></li>
        <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
        <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
        <li><%= link_to "Sign in", new_sessions_path%></li>
        <% else %>
        <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
        <li class = "has-dropdown">
          <%= link_to 'Your Disney Memories', users_path%>
            <ul class = "dropdown">
              <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
            </ul>
        </li>
        <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
        <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
        <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
        <%end %>
      </ul>
    </section>
  </nav>

  <div class="row">
    <div class="large-12 columns">
      <div class ="panel callout radius" style="margin-top:30px">
        <div class="row">
          <div class="large-3 small-12 columns" style="margin-top:30px">
            <%=image_tag "mickey.png"%>
              <div class="hide-for-small panel" style ="margin-top:30px">
                <h3>Memories</h3>
                <h5 class="subheader">This is your Disney photo collection. All your memories are stored on this page. You can also click on a photo to see were your picture was taken. If you want to add a picture to your collection without earning a badge, click the new picture button below to upload any picture.
                </h5>
                <%= link_to 'New Picture', new_picture_path(current_user) %>
              </div>
          </div>
 
          <div class="large-9 columns">
            <div class="row" style ="margin-top:30px">
                <ul class="clearing-thumbs " data-clearing>
                  <% @pictures.each do |p| %>
                    <li class="large-3 small-6 columns" style ="margin-right:0px">
                        <a href= <%= p.b_url(:original) %> >
                          <%= image_tag p.b_url(:medium)%>
                        </a>
                        <p style="margin-bottom:0px">Date: <%=p.date%></p>
                        <%if p.badge%>
                         <td>Badge: <a href="#" data-reveal-id="myModal"><%=p.badge.name%></a>
                          <div id="myModal" class="reveal-modal" data-reveal>
                          <div id="badge_earned"></div>
                          <a class="close-reveal-modal">&#215;</a>
                        </div>
                         </td>
                         <%else%>
                         <td>Badge: n/a</td>
                        <%end%>
                           <br>
                           <a href="#" data-reveal-id="myModal">Location</a>
                            <div id="myModal" class="reveal-modal" data-reveal>
                              <div id="map-canvas2"></div>
                            <a class="close-reveal-modal">&#215;</a>
                            </div>
                           <br>
                        <%= link_to 'Delete',p, method: :delete%>
                    </li>
                  <% end %>
                </ul>
              </div>
          </div><!--close the large 9 columns  -->
        </div>
      </div>
    </div><!--close the large 12 columns -->
  </div><!--close the row -->

  <div class="row">  
    <div class="digg_pagination">
        <div class="page_info" >
          <%= page_entries_info @pictures %>
        </div>
        <%= will_paginate @pictures, :container => false %>
      </div>
  </div>

  <footer class="row">
    <div class="large-12 columns"><hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright no one at all. Go to town.</p>
        </div>
      </div>
    </div>
  </footer>
</body>

<script type="text/javascript">

    handler = Gmaps.build('Google');

    handler.buildMap ({ provider: {zoom: 16, provider_key: "AIzaSyDJJPOQH24cT6ETa9IZacS7NENpUt2MKzA"}, internal: {id: 'map-canvas2'}}, function(){
    <% @pictures.each do |p|%>
    markers = handler.addMarkers([
    
    {lat: <%=p.latitude%>,
    lng: <%=p.longitude%>,
  },
    
  ]);
    <%end%>
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();



});

</script>

app/views/users/new.html.erb
 <body id="signup"> 
  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>
<% flash.each do |key, value| %>
  <div data-alert class="alert-box alert">  
    <div class="alert alert-<%= key %>" style="text-align:center"><%= value %></div>
  </div>
<% end %>
    <fieldset>
        <legend>New User</legend>
    
      <%= form_for @user do |f| %>
        <label>First Name: <%= f.text_field :first_name, class: 'form-control', autofocus: true, placeholder: 'First Name' %> </label>
        <label>Last Name <%= f.text_field :last_name, class: 'form-control', autofocus: true, placeholder: 'Last Name' %></label>
        <label>Email: <%= f.text_field :email, class: 'form-control', autofocus: true, placeholder: 'your email address' %></label>
        <label>Password: <%= f.password_field :password, class: 'form-control', autofocus: true, placeholder: 'password' %></label>
        <%= f.submit "Join the fun!", class: "button tiny radius" %>
      <% end %>
    </fieldset>
</body>
		
			
		

app/views/users/show.html.erb
<!-- show pictures here -->
 <body id="">
	  <nav class="top-bar" data-topbar >
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Disney Treasure Hunt', root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if !current_user%>
      <li ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign in", new_sessions_path%></li>
      <% else %>
      <li class="active" ><%= link_to 'Badge Gallery', badges_path%></li>
      <li class = "has-dropdown">
        <%= link_to 'Your Disney Memories', users_path%>
          <ul class = "dropdown">
            <li><%= link_to 'Your Badge Collection', my_badges_path%></li>
          </ul>
      </li>
      <li class="active"><%= link_to 'Map of Badge Location', maps_path%></li>
      <li ><%= link_to 'Photo Gallery of Guests', pictures_path%></li>
      <li><%= link_to "Sign out", sessions_path, :method => :delete %></li>
      <%end %>
    </ul>
  </section>
</nav>

	<div>
	<% @pictures.each do |p| %>
	  <%= image_tag p.image.url(:medium)%>
	  <%end%>
	</div>

</body> 